### ISSUE TITLE
Question about using as a pre-processing step in downstream applications

### ISSUE THREAD

**Issue by Andrei997** [Lambda-3/DiscourseSimplification#19]
Hi, and first of all, thank you sharing this great framework. 
I was reading the original paper, and was curious about the implementation details when used as a pre-processing step, especially for the task of OPEN IE. 
I am currently facing the same task, and would like to know whether you simply applied the framework to the entirety of the input, or rather employed additional validation steps. 
Also, given the framework produces a hierarchical representation of a sentence, how did you construct the final input [i.e. did you just include the sentences in level 0, or did you also include the higher levels] ?

**Comment by Mischn** [comment]
Hi Andrei,

thanks for your interest in our research!
If you are curious in applying DIscourseSimplification to the downstream application of OpenIE,
I suggest to check out our OpenIE system ["Graphene"](https://github.com/Lambda-3/Graphene) which we built for that purpose.

Graphene is built upon DiscourseSimplification by:

1. First applying DiscourseSimplification in order to generate a hierarchy of simplified sentences.
2. Extracting OpenIE <subject, predicate, object> - relations from the simplified sentences (of all levels)

The great thing about this method is that Graphene is able to maintain semantic/rhetorical relationships between extractions from the input text.

For more information, check out our [published paper](https://www.aclweb.org/anthology/C18-1195/) at COLING 2018

**Comment by Andrei997** [comment]
Oh awesome, I did not know about Graphene. I will check it out, thank you for the input.
